# Generated by Django 4.1.7 on 2023-05-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
